let dummyData =
{
    "data": [
        {
            "id": 86,
            "timestamp": "2021-03-22T18:43:50.38",
            "title": "New Release",
            "text": "Portal has been updated to DEV0.0.0. Click or go to releases to learn more.",
            "linkTo": "/releases/",
            "type": "info",
            "expires": "2021-03-24T12:43:04",
            "recipientId": 9598,
            "notificationState": "read",
            "category": "release",
            "minAppVersion": "DEV0.0.0",
            "createdBy": "9598",
            "parentId": 55,
            "deletedBy": null,
            "deletedDateUtc": null
        },
        {
            "id": 87,
            "timestamp": "2021-03-22T19:43:30.257",
            "title": "New Release",
            "text": "Portal has been updated to test.3. Click or go to releases to learn more.",
            "linkTo": "/releases/",
            "type": "info",
            "expires": "2021-03-24T13:43:10",
            "recipientId": 9598,
            "notificationState": "unread",
            "category": "release",
            "minAppVersion": "DEV0.0.0",
            "createdBy": "9596",
            "parentId": 73,
            "deletedBy": null,
            "deletedDateUtc": null
        },
        {
            "id": 88,
            "timestamp": "2021-03-22T19:56:32.433",
            "title": "New Release",
            "text": "Portal has been updated to DEV0.0.0. Click or go to releases to learn more.",
            "linkTo": "/releases/",
            "type": "info",
            "expires": "2021-03-24T13:56:32",
            "recipientId": 9598,
            "notificationState": "read",
            "category": "release",
            "minAppVersion": "DEV0.0.0",
            "createdBy": "9598",
            "parentId": 74,
            "deletedBy": null,
            "deletedDateUtc": null
        },
        {
            "id": 89,
            "timestamp": "2021-03-22T19:58:10.287",
            "title": "New Release",
            "text": "Portal has been updated to DEV0.0.0. Click or go to releases to learn more.",
            "linkTo": "/releases/",
            "type": "info",
            "expires": "2021-03-24T13:58:09",
            "recipientId": 9598,
            "notificationState": "read",
            "category": "release",
            "minAppVersion": "DEV0.0.0",
            "createdBy": "9598",
            "parentId": 75,
            "deletedBy": null,
            "deletedDateUtc": null
        },
        {
            "id": 91,
            "timestamp": "2021-03-22T19:59:40.527",
            "title": "New Release",
            "text": "Portal has been updated to DEV0.0.0. Click or go to releases to learn more.",
            "linkTo": "/releases/",
            "type": "info",
            "expires": "2021-03-24T13:59:39",
            "recipientId": 9598,
            "notificationState": "read",
            "category": "release",
            "minAppVersion": "DEV0.0.0",
            "createdBy": "9598",
            "parentId": 90,
            "deletedBy": null,
            "deletedDateUtc": null
        },
        {
            "id": 134,
            "timestamp": "2021-03-22T20:22:23.417",
            "title": "New Release",
            "text": "Portal has been updated to 1.0.1403. Click or go to releases to learn more.",
            "linkTo": "/releases/",
            "type": "info",
            "expires": "2021-03-24T14:22:22",
            "recipientId": 9598,
            "notificationState": "read",
            "category": "release",
            "minAppVersion": "1.0.1403",
            "createdBy": "9598",
            "parentId": 98,
            "deletedBy": null,
            "deletedDateUtc": null
        },
        {
            "id": 135,
            "timestamp": "2021-03-22T20:22:40.293",
            "title": "New Release",
            "text": "Portal has been updated to 1.0.1403. Click or go to releases to learn more.",
            "linkTo": "/releases/",
            "type": "info",
            "expires": "2021-03-24T14:22:22",
            "recipientId": 9598,
            "notificationState": "read",
            "category": "release",
            "minAppVersion": "1.0.1403",
            "createdBy": "9598",
            "parentId": 99,
            "deletedBy": null,
            "deletedDateUtc": null
        },
        {
            "id": 136,
            "timestamp": "2021-03-22T20:22:40.34",
            "title": "Some other release",
            "text": "A release for specified role(s).",
            "linkTo": "/releases/",
            "type": "info",
            "expires": "2021-03-24T14:22:34",
            "recipientId": 9598,
            "notificationState": "read",
            "category": "release",
            "minAppVersion": "1.0.1403",
            "createdBy": "9598",
            "parentId": 100,
            "deletedBy": null,
            "deletedDateUtc": null
        },
        {
            "id": 137,
            "timestamp": "2021-03-22T20:22:51.51",
            "title": "New Release",
            "text": "Portal has been updated to 1.0.1403. Click or go to releases to learn more.",
            "linkTo": "/releases/",
            "type": "info",
            "expires": "2021-03-24T14:22:22",
            "recipientId": 9598,
            "notificationState": "read",
            "category": "release",
            "minAppVersion": "1.0.1403",
            "createdBy": "9598",
            "parentId": 101,
            "deletedBy": null,
            "deletedDateUtc": null
        },
        {
            "id": 138,
            "timestamp": "2021-03-22T20:22:52.397",
            "title": "Some other release",
            "text": "A release for specified role(s).",
            "linkTo": "/releases/",
            "type": "info",
            "expires": "2021-03-24T14:22:34",
            "recipientId": 9598,
            "notificationState": "read",
            "category": "release",
            "minAppVersion": "1.0.1403",
            "createdBy": "9598",
            "parentId": 102,
            "deletedBy": null,
            "deletedDateUtc": null
        },
        {
            "id": 139,
            "timestamp": "2021-03-22T20:22:52.397",
            "title": "New Release",
            "text": "Portal has been updated to 1.0.1403. Click or go to releases to learn more.",
            "linkTo": "/releases/",
            "type": "info",
            "expires": "2021-03-24T14:22:22",
            "recipientId": 9598,
            "notificationState": "read",
            "category": "release",
            "minAppVersion": "1.0.1403",
            "createdBy": "9598",
            "parentId": 103,
            "deletedBy": null,
            "deletedDateUtc": null
        },
        {
            "id": 140,
            "timestamp": "2021-03-22T20:22:52.38",
            "title": "Some other release",
            "text": "A release for specified role(s).",
            "linkTo": "/releases/",
            "type": "info",
            "expires": "2021-03-24T14:22:34",
            "recipientId": 9598,
            "notificationState": "read",
            "category": "release",
            "minAppVersion": "1.0.1403",
            "createdBy": "9598",
            "parentId": 104,
            "deletedBy": null,
            "deletedDateUtc": null
        },
        {
            "id": 141,
            "timestamp": "2021-03-22T20:22:54.09",
            "title": "New Release",
            "text": "Portal has been updated to 1.5. Click or go to releases to learn more.",
            "linkTo": "/releases/",
            "type": "info",
            "expires": "2021-03-24T14:22:53",
            "recipientId": 9598,
            "notificationState": "read",
            "category": "release",
            "minAppVersion": "1.0",
            "createdBy": "9596",
            "parentId": 105,
            "deletedBy": null,
            "deletedDateUtc": null
        },
        {
            "id": 142,
            "timestamp": "2021-03-22T20:23:35.6",
            "title": "New Release",
            "text": "Portal has been updated to 1.0.1403. Click or go to releases to learn more.",
            "linkTo": "/releases/",
            "type": "info",
            "expires": "2021-03-24T14:22:22",
            "recipientId": 9598,
            "notificationState": "read",
            "category": "release",
            "minAppVersion": "1.0.1403",
            "createdBy": "9598",
            "parentId": 114,
            "deletedBy": null,
            "deletedDateUtc": null
        },
        {
            "id": 143,
            "timestamp": "2021-03-22T20:23:36.71",
            "title": "Some other release",
            "text": "A release for specified role(s).",
            "linkTo": "/releases/",
            "type": "info",
            "expires": "2021-03-24T14:22:34",
            "recipientId": 9598,
            "notificationState": "read",
            "category": "release",
            "minAppVersion": "1.0.1403",
            "createdBy": "9598",
            "parentId": 115,
            "deletedBy": null,
            "deletedDateUtc": null
        },
        {
            "id": 144,
            "timestamp": "2021-03-22T20:24:32.57",
            "title": "New Release",
            "text": "Portal has been updated to 1.0.1403. Click or go to releases to learn more.",
            "linkTo": "/releases/",
            "type": "info",
            "expires": "2021-03-24T14:22:22",
            "recipientId": 9598,
            "notificationState": "read",
            "category": "release",
            "minAppVersion": "1.0.1403",
            "createdBy": "9598",
            "parentId": 116,
            "deletedBy": null,
            "deletedDateUtc": null
        },
        {
            "id": 145,
            "timestamp": "2021-03-22T20:24:32.57",
            "title": "Some other release",
            "text": "A release for specified role(s).",
            "linkTo": "/releases/",
            "type": "info",
            "expires": "2021-03-24T14:22:34",
            "recipientId": 9598,
            "notificationState": "read",
            "category": "release",
            "minAppVersion": "1.0.1403",
            "createdBy": "9598",
            "parentId": 117,
            "deletedBy": null,
            "deletedDateUtc": null
        },
        {
            "id": 146,
            "timestamp": "2021-03-22T20:24:59.86",
            "title": "New Release",
            "text": "Portal has been updated to 1.0.1403. Click or go to releases to learn more.",
            "linkTo": "/releases/",
            "type": "info",
            "expires": "2021-03-24T14:22:22",
            "recipientId": 9598,
            "notificationState": "read",
            "category": "release",
            "minAppVersion": "1.0.1403",
            "createdBy": "9598",
            "parentId": 118,
            "deletedBy": null,
            "deletedDateUtc": null
        },
        {
            "id": 147,
            "timestamp": "2021-03-22T20:24:59.783",
            "title": "Some other release",
            "text": "A release for specified role(s).",
            "linkTo": "/releases/",
            "type": "info",
            "expires": "2021-03-24T14:22:34",
            "recipientId": 9598,
            "notificationState": "read",
            "category": "release",
            "minAppVersion": "1.0.1403",
            "createdBy": "9598",
            "parentId": 119,
            "deletedBy": null,
            "deletedDateUtc": null
        },
        {
            "id": 148,
            "timestamp": "2021-03-22T20:25:07.423",
            "title": "Some other release",
            "text": "A release for specified role(s).",
            "linkTo": "/releases/",
            "type": "info",
            "expires": "2021-03-24T14:22:34",
            "recipientId": 9598,
            "notificationState": "read",
            "category": "release",
            "minAppVersion": "1.0.1403",
            "createdBy": "9598",
            "parentId": 120,
            "deletedBy": null,
            "deletedDateUtc": null
        },
        {
            "id": 149,
            "timestamp": "2021-03-22T20:25:07.703",
            "title": "New Release",
            "text": "Portal has been updated to 1.0.1403. Click or go to releases to learn more.",
            "linkTo": "/releases/",
            "type": "info",
            "expires": "2021-03-24T14:22:22",
            "recipientId": 9598,
            "notificationState": "read",
            "category": "release",
            "minAppVersion": "1.0.1403",
            "createdBy": "9598",
            "parentId": 121,
            "deletedBy": null,
            "deletedDateUtc": null
        },
        {
            "id": 150,
            "timestamp": "2021-03-22T20:28:36.79",
            "title": "Some other release",
            "text": "A release for specified role(s).",
            "linkTo": "/releases/",
            "type": "info",
            "expires": "2021-03-24T14:22:34",
            "recipientId": 9598,
            "notificationState": "read",
            "category": "release",
            "minAppVersion": "1.0.1403",
            "createdBy": "9598",
            "parentId": 122,
            "deletedBy": null,
            "deletedDateUtc": null
        },
        {
            "id": 151,
            "timestamp": "2021-03-22T20:28:37.07",
            "title": "New Release",
            "text": "Portal has been updated to 1.0.1403. Click or go to releases to learn more.",
            "linkTo": "/releases/",
            "type": "info",
            "expires": "2021-03-24T14:22:22",
            "recipientId": 9598,
            "notificationState": "read",
            "category": "release",
            "minAppVersion": "1.0.1403",
            "createdBy": "9598",
            "parentId": 123,
            "deletedBy": null,
            "deletedDateUtc": null
        },
        {
            "id": 153,
            "timestamp": "2021-03-22T20:46:30.363",
            "title": "New Release",
            "text": "Portal has been updated to 1.0. Click or go to releases to learn more.",
            "linkTo": "/releases/",
            "type": "info",
            "expires": "2021-03-24T14:46:29",
            "recipientId": 9598,
            "notificationState": "read",
            "category": "release",
            "minAppVersion": "0.55",
            "createdBy": "9596",
            "parentId": 152,
            "deletedBy": null,
            "deletedDateUtc": null
        },
        {
            "id": 155,
            "timestamp": "2021-03-22T20:48:50.363",
            "title": "New Release",
            "text": "Portal has been updated to 1.0. Click or go to releases to learn more.",
            "linkTo": "/releases/",
            "type": "info",
            "expires": "2021-03-24T14:46:29",
            "recipientId": 9598,
            "notificationState": "read",
            "category": "release",
            "minAppVersion": "0.55",
            "createdBy": "9596",
            "parentId": 154,
            "deletedBy": null,
            "deletedDateUtc": null
        },
        {
            "id": 157,
            "timestamp": "2021-03-22T20:51:43.753",
            "title": "New Release",
            "text": "Portal has been updated to 1.0. Click or go to releases to learn more.",
            "linkTo": "/releases/",
            "type": "info",
            "expires": "2021-03-24T14:46:29",
            "recipientId": 9598,
            "notificationState": "read",
            "category": "release",
            "minAppVersion": "0.55",
            "createdBy": "9596",
            "parentId": 156,
            "deletedBy": null,
            "deletedDateUtc": null
        },
        {
            "id": 160,
            "timestamp": "2021-03-22T20:52:06.297",
            "title": "New Release",
            "text": "Portal has been updated to 1.0. Click or go to releases to learn more.",
            "linkTo": "/releases/",
            "type": "info",
            "expires": "2021-03-24T14:46:29",
            "recipientId": 9598,
            "notificationState": "read",
            "category": "release",
            "minAppVersion": "0.55",
            "createdBy": "9596",
            "parentId": 158,
            "deletedBy": null,
            "deletedDateUtc": null
        },
        {
            "id": 161,
            "timestamp": "2021-03-22T20:52:06.35",
            "title": "New Release",
            "text": "Portal has been updated to 1.0. Click or go to releases to learn more.",
            "linkTo": "/releases/",
            "type": "info",
            "expires": "2021-03-24T14:46:29",
            "recipientId": 9598,
            "notificationState": "read",
            "category": "release",
            "minAppVersion": "0.55",
            "createdBy": "9596",
            "parentId": 159,
            "deletedBy": null,
            "deletedDateUtc": null
        },
        {
            "id": 176,
            "timestamp": "2021-03-22T21:01:28.763",
            "title": "Some other release",
            "text": "A release for specified role(s).",
            "linkTo": "/releases/",
            "type": "info",
            "expires": "2021-03-24T15:01:11",
            "recipientId": 9598,
            "notificationState": "read",
            "category": "release",
            "minAppVersion": "DEV0.0.0",
            "createdBy": "9598",
            "parentId": 167,
            "deletedBy": null,
            "deletedDateUtc": null
        },
        {
            "id": 177,
            "timestamp": "2021-03-22T21:03:27.653",
            "title": "Some other release",
            "text": "A release for specified role(s).",
            "linkTo": "/releases/",
            "type": "info",
            "expires": "2021-03-24T15:01:11",
            "recipientId": 9598,
            "notificationState": "read",
            "category": "release",
            "minAppVersion": "DEV0.0.0",
            "createdBy": "9598",
            "parentId": 168,
            "deletedBy": null,
            "deletedDateUtc": null
        },
        {
            "id": 178,
            "timestamp": "2021-03-22T21:03:43.283",
            "title": "New Release",
            "text": "Portal has been updated to DEV0.0.0. Click or go to releases to learn more.",
            "linkTo": "/releases/",
            "type": "info",
            "expires": "2021-03-24T15:03:41",
            "recipientId": 9598,
            "notificationState": "read",
            "category": "release",
            "minAppVersion": "DEV0.0.0",
            "createdBy": "9598",
            "parentId": 169,
            "deletedBy": null,
            "deletedDateUtc": null
        },
        {
            "id": 179,
            "timestamp": "2021-03-22T21:03:58.897",
            "title": "Some other release",
            "text": "A release for specified role(s).",
            "linkTo": "/releases/",
            "type": "info",
            "expires": "2021-03-24T15:03:28",
            "recipientId": 9598,
            "notificationState": "read",
            "category": "release",
            "minAppVersion": "DEV0.0.0",
            "createdBy": "9598",
            "parentId": 170,
            "deletedBy": null,
            "deletedDateUtc": null
        },
        {
            "id": 180,
            "timestamp": "2021-03-22T21:03:59.24",
            "title": "New Release",
            "text": "Portal has been updated to DEV0.0.0. Click or go to releases to learn more.",
            "linkTo": "/releases/",
            "type": "info",
            "expires": "2021-03-24T15:03:41",
            "recipientId": 9598,
            "notificationState": "read",
            "category": "release",
            "minAppVersion": "DEV0.0.0",
            "createdBy": "9598",
            "parentId": 171,
            "deletedBy": null,
            "deletedDateUtc": null
        },
        {
            "id": 181,
            "timestamp": "2021-03-22T21:03:59.787",
            "title": "Some other release",
            "text": "A release for specified role(s).",
            "linkTo": "/releases/",
            "type": "info",
            "expires": "2021-03-24T15:01:11",
            "recipientId": 9598,
            "notificationState": "read",
            "category": "release",
            "minAppVersion": "DEV0.0.0",
            "createdBy": "9598",
            "parentId": 172,
            "deletedBy": null,
            "deletedDateUtc": null
        },
        {
            "id": 182,
            "timestamp": "2021-03-22T21:04:06.503",
            "title": "Some other release",
            "text": "A release for specified role(s).",
            "linkTo": "/releases/",
            "type": "info",
            "expires": "2021-03-24T15:03:28",
            "recipientId": 9598,
            "notificationState": "read",
            "category": "release",
            "minAppVersion": "DEV0.0.0",
            "createdBy": "9598",
            "parentId": 173,
            "deletedBy": null,
            "deletedDateUtc": null
        },
        {
            "id": 183,
            "timestamp": "2021-03-22T21:04:06.927",
            "title": "New Release",
            "text": "Portal has been updated to DEV0.0.0. Click or go to releases to learn more.",
            "linkTo": "/releases/",
            "type": "info",
            "expires": "2021-03-24T15:03:41",
            "recipientId": 9598,
            "notificationState": "read",
            "category": "release",
            "minAppVersion": "DEV0.0.0",
            "createdBy": "9598",
            "parentId": 174,
            "deletedBy": null,
            "deletedDateUtc": null
        },
        {
            "id": 184,
            "timestamp": "2021-03-22T21:04:06.537",
            "title": "Some other release",
            "text": "A release for specified role(s).",
            "linkTo": "/releases/",
            "type": "info",
            "expires": "2021-03-24T15:01:11",
            "recipientId": 9598,
            "notificationState": "read",
            "category": "release",
            "minAppVersion": "DEV0.0.0",
            "createdBy": "9598",
            "parentId": 175,
            "deletedBy": null,
            "deletedDateUtc": null
        },
        {
            "id": 195,
            "timestamp": "2021-03-22T22:11:41.527",
            "title": "New Release",
            "text": "Portal has been updated to 1.0.1404. Click or go to releases to learn more.",
            "linkTo": "/releases/",
            "type": "info",
            "expires": "2021-03-24T16:11:41",
            "recipientId": 9598,
            "notificationState": "new",
            "category": "release",
            "minAppVersion": "1.0.1404",
            "createdBy": "9598",
            "parentId": 194,
            "deletedBy": null,
            "deletedDateUtc": null
        },
        {
            "id": 198,
            "timestamp": "2021-03-22T22:32:18.853",
            "title": "New Release",
            "text": "Portal has been updated to 6.0. Click or go to releases to learn more.",
            "linkTo": "/releases/",
            "type": "info",
            "expires": "2021-03-24T16:31:16",
            "recipientId": 9598,
            "notificationState": "new",
            "category": "release",
            "minAppVersion": "3.4",
            "createdBy": "9596",
            "parentId": 197,
            "deletedBy": null,
            "deletedDateUtc": null
        }
    ],
    "status": 200,
    "statusText": "OK",
    "headers": {
        "cache-control": "no-cache",
        "content-length": "1663",
        "content-type": "application/json; charset=utf-8",
        "expires": "-1",
        "pragma": "no-cache"
    },
    "config": {
        "url": "https://launchpointportalapi-dev.lp-ase.appserviceenvironment.net/api/User/Notifications?userId=9598&category=release",
        "method": "get",
        "headers": {
            "Accept": "application/json, text/plain, */*",
            "authorization": "bearer acBML2jcLoS96LSnHQ87Gdvm4RfWEcPxlDWBK8lYfUBS8MV-Os_fql8yvs3dGpkZlDUGY8tZrC7jSt9Jyeh8XP-CC1Wl7DSNEvjZLSDfWlHt0_A7ISgdti2h_ou0zFlXmNt-MYpPTmZ5_Xnd0lFqKMjvwvd56fMa3PRFscmb8CKR7EYpd8xMRi9OjjjwcpKLbiKBELVu1pkg0-ccJq1KUAZBrWWqN14SOh1u56vJTuP_wYIvQEk37z2z84OmNFHjmsbxO7baoXksbFS6uEMDKeFLIkHoLBKEPFVtz2Cfypdf6qTohozfgN7Ot9WjmMM32PUsZ0tO7GzYBN9Y3Man3L_B5MnG-tFHNbbz2nFZUxYwLNWBiSmWcpLJxRUzyRjjBI52Xkv572jxP_E1x9tTjd0hErqD05wIvyZ3ABEpcZBS92c_ZuPa_mc3dmC-dT5HyvVwz1oiE2MVTB1PAur8PvwMzCSqdlYcj3yf4Qkr9mChcbZhfWVpXm0c8eiSc_KU_DcJvuIR1hAKKihF6pYgJXynNEW3cEU--kiKChY_Ccgq_tY7HbeR7dbfelS4LWUAsXnSlsWwuPBZBTyjn7gmuhl4QGBafcO1GPj47depE0CjXzlRIHztnXs2xxROCV_Bve638mQ5Hhe17d0Ciwdbcxsa3OrOkPvcpbna8-sXjAW45MS1aZMUVDXuTC3wMHww"
        },
        "transformRequest": [
            null
        ],
        "transformResponse": [
            null
        ],
        "timeout": 0,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1
    },
    "request": {}
}

export default dummyData